name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      # Checkout repository & Setup git credentials
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      # Setup python
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Setup uv
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      # Install dependencies
      - name: Install dependencies
        run: uv sync --all-groups

      # Setup cache & Deploy
      - name: Prepare cache setup
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Setup cache to improve workflow execution time
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Deploy
        run: uv run mkdocs gh-deploy --force
